
chanlocs = struct('labels', { ...
                                          'Nz',...
                                    'Fp1','Fpz','Fp2',...
                              'AF7','AF3','AFz','AF4','AF8',...
                        'F5' ,'F3' ,'F1' ,'Fz' ,'F2' ,'F4' ,'F6',...
                  'FT7','FC5','FC3','FC1','FCz','FC2','FC4','FC6','FT8',...
            'T9' ,'T7' ,'C5' ,'C3' ,'C1' ,'Cz' ,'C2' ,'C4' ,'C6' ,'T8' ,'T10' ,...
                  'TP7','CP5','CP3','CP1','CPz','CP2','CP4','CP6','TP8',...
                         'P5' ,'P3' ,'P1' ,'Pz' ,'P2' ,'P4' ,'P6' ,...
                               'PO7','PO3','POz','PO4','PO8',...
                                      'O1' ,'Oz' ,'O2'}); 
pop_chanedit( chanlocs );

load('SSL_DATA_DEFAULT');

M = load('SSL_MODEL_DEFAULT');

X = ssltool(s,M)

[s, com, b] = pop_eegfiltnew(s, 8, 30)